const chores = [
  "Dance on the ceiling",
  "Sing while vacuuming",
  "Fold laundry blindfolded",
  "Water the plants while spinning",
  "Sweep the floor like a ninja",
  "Wash dishes while screaming",
  "Polish the doorknobs",
  "Sort the laundry alphabetically",
  "Make the bed with a somersault"
  // the above chores were generated by ai since i dont wanna spend an hour thinking on chores
];

const choreButton = document.getElementById("generate");
const choreDisplay = document.getElementById("chore");

choreButton.addEventListener("click", () => {
  const randomIndex = Math.floor(Math.random() * chores.length);
  choreDisplay.textContent = chores[randomIndex];
});
